export const USER_SINGIN_API = "USER_SINGIN_API";
export const USLOGIN = "USLOGIN";

export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";
export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";
